name: Build & upload to Firebase App Distribution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  firebase-app-distribution:

    name: Upload build to firebase appDistribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Create google-services.json file
        run: cat /home/runner/work/FoodDeliveryApp/FoodDeliveryApp/app/google-services.json | base64
      - name: Put data into google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/FoodDeliveryApp/FoodDeliveryApp/app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build release
        run: ./gradlew assembleRelease
      - name: Upload artifact to firebase appDistribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk